name: data_queue
description: This package provides the DataQueue - an asynchronous pull-based class for accessing data.
version: 1.0.1
homepage: https://github.com/KirsApps/data_queue

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0
